# Config file for automatic testing at travis-ci.org
language: python

services:
  - postgresql

env:
  global : DATABASE_URL=postgres://postgres:@127.0.0.1:5432

matrix:
    include:
      # Python version is just for the look on travis.
        - python: 2.7
          env: TOX_ENV=py27-django18

        - python: 2.7
          env: TOX_ENV=py27-django19

        - python: 2.7
          env: TOX_ENV=py27-django110

        - python: 2.7
          env: TOX_ENV=py27-django111

        - python: 2.7
          env: TOX_ENV=py27-djangostable

        - python: 3.4
          env: TOX_ENV=py34-django18

        - python: 3.4
          env: TOX_ENV=py34-django19

        - python: 3.4
          env: TOX_ENV=py34-django110

        - python: 3.4
          env: TOX_ENV=py34-django111

        - python: 3.4
          env: TOX_ENV=py34-djangostable

        - python: 3.5
          env: TOX_ENV=py35-django18

        - python: 3.5
          env: TOX_ENV=py35-django19

        - python: 3.5
          env: TOX_ENV=py35-django110

        - python: 3.5
          env: TOX_ENV=py35-django111

        - python: 3.5
          env: TOX_ENV=py35-djangostable

        - python: 3.6
          env: TOX_ENV=py36-django111

        - python: 3.6
          env: TOX_ENV=py36-djangostable

        - env: TOX_ENV=linters

install:
  - pip install tox codecov

script:
  - tox -e $TOX_ENV

after_success:
  - codecov
